---
layout: cv
title: Julian Hernandez Resume
---
# Contact Information
• her22004@byui.edu • +1 (208) 403-4913

<div id="webaddress">
<a href="https://www.linkedin.com/in/julian-hernandez-3bb6a7212/">LinkedIn</a>

## Experienced Computer Science Student

- Created and optimized multiple Python C# programs.
- Implemented object-oriented programming principles to programs effectively.
- Worked with APIs and with their use on programs.
- Designed and tested multiple algorithms for each program created, finding the most efficient.


### Education

`2021-2026`
Brigham Young University - Idaho

- Computer Science, Data Science. GPA: 4.0
- Relevant Coursework: Web Fundamentals, Algorithm Design and Applied Programming.

`Graduate in 2020`
Colegio Príncipe San Carlos

- GPA: 4.0v
- Graduated with Academic Honors.
- Successful completion of “Home on the Moon” project from the Aldrin Foundation.

### Technical Skills & Interests

- Technical: SQL, MySQL, SQLiteStudio, JavaScript, Python, C#, C++, Java, Rust, HTML, CSS, Python Pandas and Python sqlite3.
- Languages: Fully fluent in English and Spanish.
- Interests: Pixel Art, Piano, Game Development, Data Science, Databases and Music Composing.

## Leadership & Activities

`2024-2024`
__BYU-I Data Science Society, Centenario Project Member__

- Analyzed data from a foreign car renting company and discerned for relevant metrics.
- Introduced myself into the team, only needing a week to start producing results in a foreign environment.
- Organized all the relevant data into a report to be presented to the car renting company.

`2019-2024`
__Revenant Division, Co-Administrator__

- Led a team of people from different backgrounds and countries for a common goal.
- Successfully resolved issues from multiple members in the community.

## Experience

`2023-2024`
__Teleperformance, English/Spanish Interpreter__

- Relayed information in high-stress situations between two parties who didn’t understand each other with an exactitude of 95%.
- Maintained professional attitude in despite of attitudes other parties had 100% of the time.
- Recorded information in a fast-paced environment that came from different sources with only a 5% loss in translation.

<!-- ### Footer

Last updated: May 2024 -->