---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "Julian Hernandez"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_The most important part of this project was familarizing myself with the python libraries and the way quarto works. Added to that the first chart shows that smaller engine sizes are more fuel efficent and vice-versa. Also, creating the table showed me the value of cleaning data to workable chunks for better analysis. This summarizes the key insights from this project._

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
mpg = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/mpg/mpg.csv")
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__In VS Code, create the example chart from section 3.2.2 of the textbook.__

_The scatter plot shows a negative relationship between fuel efficency and engine size. So this means that cars with smaller engines use less fuel and cars with bigger engines use more fuel._

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
chart1 = px.scatter(
    mpg,
    x='displ', 
    y='hwy'
)
chart1.show()
```

## QUESTION|TASK 2

__Your final report should also include the table created from the following:__

_Through making this table work I learned how to shorten data into more concise tables that might show me more relevant data with which I can work off to get different types of results from analysis. This table shortens the relevant data to the manufacturer, model, year and hwy columns._

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here
table1 = (mpg
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
)
table1
```